# Porto Seguroâ€™s Safe Driver Prediction

Import module

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
sns.set()

Load train and test dataset from local drive

In [54]:
df_train = pd.read_csv('../train.csv', engine='python')
df_test = pd.read_csv('../test.csv', engine='python')
df_test

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,0,1,8,1,0,0,1,0,0,...,1,1,1,12,0,1,1,0,0,1
1,1,4,2,5,1,0,0,0,0,1,...,2,0,3,10,0,0,1,1,0,1
2,2,5,1,3,0,0,0,0,0,1,...,4,0,2,4,0,0,0,0,0,0
3,3,0,1,6,0,0,1,0,0,0,...,5,1,0,5,1,0,1,0,0,0
4,4,5,1,7,0,0,0,0,0,1,...,4,0,0,4,0,1,1,0,0,1
5,5,0,1,6,0,0,1,0,0,0,...,8,1,4,9,1,0,1,0,1,0
6,6,0,1,3,0,0,0,1,0,0,...,2,0,4,6,1,1,0,0,0,0
7,8,0,1,0,0,0,1,0,0,0,...,3,1,4,9,0,1,0,0,0,0
8,10,0,1,7,0,0,0,1,0,0,...,5,1,4,6,0,0,1,0,0,0
9,11,1,1,6,0,0,0,0,0,1,...,6,1,6,10,0,1,1,0,0,0
10,12,0,1,5,0,4,1,0,0,0,...,2,1,1,8,0,1,1,1,0,0
11,14,1,1,4,0,0,1,0,0,0,...,4,2,7,8,0,1,0,1,0,0
12,15,1,1,2,1,0,0,1,0,0,...,3,4,0,12,1,1,0,0,1,0
13,18,3,1,3,0,0,0,1,0,0,...,7,0,5,9,0,0,0,1,0,0
14,21,0,2,1,0,6,1,0,0,0,...,6,3,5,6,0,0,1,0,0,0
15,23,2,2,2,0,0,0,0,1,0,...,9,0,2,11,0,0,1,1,0,0
16,24,2,1,3,0,0,0,0,1,0,...,3,1,2,8,0,1,1,0,0,0
17,25,0,2,0,1,-1,1,0,0,0,...,5,2,3,9,1,1,1,0,1,0
18,27,3,2,1,0,0,1,0,0,0,...,4,3,5,9,0,1,1,0,1,0
19,29,1,1,4,1,6,0,1,0,0,...,3,2,2,6,0,0,1,0,0,0
20,30,0,1,4,0,0,1,0,0,0,...,3,1,4,6,1,1,0,1,0,0
21,31,6,2,1,0,0,0,0,0,1,...,4,2,4,7,0,1,0,0,1,0
22,32,0,1,8,0,0,0,1,0,0,...,2,0,4,10,0,0,1,1,0,0
23,33,1,1,2,0,0,1,0,0,0,...,9,0,6,7,1,1,0,1,0,0
24,37,5,2,6,1,0,0,0,0,1,...,9,2,4,5,0,1,0,1,0,0
25,38,1,2,0,1,0,0,1,0,0,...,7,3,2,6,0,1,1,1,0,0
26,39,5,2,2,1,0,0,0,1,0,...,3,0,7,8,0,1,0,1,0,1
27,40,1,1,3,0,0,1,0,0,0,...,6,3,2,8,0,0,1,1,0,0
28,41,0,1,1,1,0,0,1,0,0,...,7,2,4,5,0,1,1,0,1,0
29,42,1,2,7,1,0,1,0,0,0,...,4,2,2,4,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892786,1487982,2,1,3,0,0,1,0,0,0,...,8,0,1,8,0,1,1,0,1,1
892787,1487984,1,1,2,1,0,1,0,0,0,...,9,0,2,4,0,1,1,0,1,0
892788,1487985,3,1,3,0,0,0,0,1,0,...,14,2,3,6,1,1,1,0,1,1
892789,1487986,1,2,1,1,0,0,0,0,1,...,5,0,1,7,1,0,0,0,1,0
892790,1487987,0,3,5,1,0,0,0,1,0,...,10,2,2,5,0,1,1,0,0,1
892791,1487989,1,1,8,0,0,1,0,0,0,...,7,0,6,4,0,1,0,1,0,1
892792,1487991,1,1,6,0,0,1,0,0,0,...,3,1,3,4,0,0,0,1,0,0
892793,1487993,0,2,1,0,6,1,0,0,0,...,5,2,2,5,0,0,1,0,0,0
892794,1487995,6,2,7,0,0,0,0,0,1,...,10,3,2,6,0,1,1,0,0,0
892795,1487997,2,1,8,0,0,0,0,0,1,...,12,2,3,11,0,1,0,0,1,1
892796,1487998,0,2,1,1,0,0,1,0,0,...,4,1,1,3,0,0,1,0,1,0
892797,1487999,2,1,5,0,6,0,0,1,0,...,9,2,2,13,0,1,0,0,0,0
892798,1488000,7,1,4,0,0,0,0,0,1,...,8,2,2,7,0,0,0,0,0,0
892799,1488002,0,2,0,0,-1,1,0,0,0,...,7,0,4,9,0,1,1,0,0,0
892800,1488003,1,1,2,1,0,0,1,0,0,...,3,1,2,7,0,1,1,0,0,0
892801,1488004,0,1,7,0,0,1,0,0,0,...,7,3,4,7,1,1,0,0,1,0
892802,1488006,2,1,2,1,0,0,1,0,0,...,6,1,3,10,0,1,1,0,1,0
892803,1488007,3,1,2,1,0,1,0,0,0,...,6,1,2,8,0,0,1,1,1,0
892804,1488010,4,1,6,0,0,1,0,0,0,...,5,0,3,10,0,1,1,1,1,0
892805,1488012,5,1,6,0,0,1,0,0,0,...,6,0,0,7,0,0,1,0,0,0
892806,1488014,0,1,6,1,0,1,0,0,0,...,5,2,5,10,0,0,1,1,0,0
892807,1488015,0,1,3,0,0,0,1,0,0,...,4,3,3,6,0,0,0,1,1,0
892808,1488018,1,1,6,0,4,1,0,0,0,...,7,1,2,4,0,0,1,1,1,0
892809,1488019,2,1,7,0,0,0,0,0,1,...,7,4,3,5,0,1,1,0,0,0
892810,1488020,0,1,6,0,0,0,0,0,1,...,2,3,5,7,0,1,1,1,1,1
892811,1488022,0,1,6,0,0,0,1,0,0,...,4,2,3,4,0,1,0,0,1,0
892812,1488023,5,3,5,1,0,0,0,1,0,...,6,2,2,11,0,0,1,1,0,0
892813,1488024,0,1,5,0,0,1,0,0,0,...,5,2,2,11,0,1,1,0,0,0
892814,1488025,6,1,5,1,0,0,0,0,1,...,1,1,2,7,1,1,0,0,0,0
892815,1488026,7,1,4,1,0,0,0,0,1,...,5,2,2,7,0,1,1,1,0,0

see the head of the train dataframe

In [15]:
df_train.head()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0

the description of the dataset said that value of -1 indicate that the features was missing from observation, so I decided to replace -1 with median by each column

In [36]:
col_list = list(df_train)

for i in col_list:
    df_train[i].replace(-1, df_train[i].median())

droping some unused features or columns before I train the model

In [45]:
target = df_train.target
train = df_train.drop(['target', 'id'], axis=1)
train.head()

,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,2,2,5,1,0,0,1,0,0,0,...,9,1,5,8,0,1,1,0,0,1
1,1,1,7,0,0,0,0,1,0,0,...,3,1,1,9,0,1,1,0,1,0
2,5,4,9,1,0,0,0,1,0,0,...,4,2,7,7,0,1,1,0,1,0
3,0,1,2,0,0,1,0,0,0,0,...,2,2,4,9,0,0,0,0,0,0
4,0,2,0,1,0,1,0,0,0,0,...,3,1,1,3,0,0,0,1,1,0

see the columns name of the dataframe in list form

In [47]:
list(train)

['ps_ind_01',
 'ps_ind_02_cat',
 'ps_ind_03',
 'ps_ind_04_cat',
 'ps_ind_05_cat',
 'ps_ind_06_bin',
 'ps_ind_07_bin',
 'ps_ind_08_bin',
 'ps_ind_09_bin',
 'ps_ind_10_bin',
 'ps_ind_11_bin',
 'ps_ind_12_bin',
 'ps_ind_13_bin',
 'ps_ind_14',
 'ps_ind_15',
 'ps_ind_16_bin',
 'ps_ind_17_bin',
 'ps_ind_18_bin',
 'ps_reg_01',
 'ps_reg_02',
 'ps_reg_03',
 'ps_car_01_cat',
 'ps_car_02_cat',
 'ps_car_03_cat',
 'ps_car_04_cat',
 'ps_car_05_cat',
 'ps_car_06_cat',
 'ps_car_07_cat',
 'ps_car_08_cat',
 'ps_car_09_cat',
 'ps_car_10_cat',
 'ps_car_11_cat',
 'ps_car_11',
 'ps_car_12',
 'ps_car_13',
 'ps_car_14',
 'ps_car_15',
 'ps_calc_01',
 'ps_calc_02',
 'ps_calc_03',
 'ps_calc_04',
 'ps_calc_05',
 'ps_calc_06',
 'ps_calc_07',
 'ps_calc_08',
 'ps_calc_09',
 'ps_calc_10',
 'ps_calc_11',
 'ps_calc_12',
 'ps_calc_13',
 'ps_calc_14',
 'ps_calc_15_bin',
 'ps_calc_16_bin',
 'ps_calc_17_bin',
 'ps_calc_18_bin',
 'ps_calc_19_bin',
 'ps_calc_20_bin']

Splitting dataframe into X (features matrix) and y (target label)

In [48]:
from sklearn.model_selection import train_test_split

# split dataset 
X = train.valuesa
y = target.values

Splitting X and y into train data and 20% test data

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

training model with naive bayes algorithm

In [50]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB(priors=None)

check the accuracy score of trained naive bayes model with sklearn.metrics module

In [51]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, model.predict(X_test))

0.9064539704140521

see classification_report of trained naive bayes model with classification_report

In [52]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.97      0.94      0.95    114658
          1       0.07      0.14      0.10      4385

avg / total       0.93      0.91      0.92    119043

See confusion_matrix of trained naive bayes model with sklearn.metrics.confusion_matrix

In [53]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[107312,   7346],
       [  3790,    595]], dtype=int64)